# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _pyncptl
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


ncptl_fatal = _pyncptl.ncptl_fatal
ncptl_allocate_timing_flag = _pyncptl.ncptl_allocate_timing_flag
ncptl_reset_timing_flag = _pyncptl.ncptl_reset_timing_flag
ncptl_test_timing_flag = _pyncptl.ncptl_test_timing_flag
ncptl_free_timing_flag = _pyncptl.ncptl_free_timing_flag
NCPTL_RUN_TIME_VERSION = _pyncptl.NCPTL_RUN_TIME_VERSION
PRId64 = _pyncptl.PRId64
PRIu64 = _pyncptl.PRIu64
PRIx64 = _pyncptl.PRIx64
NICS = _pyncptl.NICS
NCPTL_FUNC_NO_AGGREGATE = _pyncptl.NCPTL_FUNC_NO_AGGREGATE
NCPTL_FUNC_MEAN = _pyncptl.NCPTL_FUNC_MEAN
NCPTL_FUNC_HARMONIC_MEAN = _pyncptl.NCPTL_FUNC_HARMONIC_MEAN
NCPTL_FUNC_GEOMETRIC_MEAN = _pyncptl.NCPTL_FUNC_GEOMETRIC_MEAN
NCPTL_FUNC_MEDIAN = _pyncptl.NCPTL_FUNC_MEDIAN
NCPTL_FUNC_STDEV = _pyncptl.NCPTL_FUNC_STDEV
NCPTL_FUNC_VARIANCE = _pyncptl.NCPTL_FUNC_VARIANCE
NCPTL_FUNC_SUM = _pyncptl.NCPTL_FUNC_SUM
NCPTL_FUNC_MINIMUM = _pyncptl.NCPTL_FUNC_MINIMUM
NCPTL_FUNC_MAXIMUM = _pyncptl.NCPTL_FUNC_MAXIMUM
NCPTL_FUNC_FINAL = _pyncptl.NCPTL_FUNC_FINAL
NCPTL_FUNC_ONLY = _pyncptl.NCPTL_FUNC_ONLY
NCPTL_FUNC_HISTOGRAM = _pyncptl.NCPTL_FUNC_HISTOGRAM
ncptl_init = _pyncptl.ncptl_init
ncptl_finalize = _pyncptl.ncptl_finalize
ncptl_fill_buffer = _pyncptl.ncptl_fill_buffer
ncptl_verify = _pyncptl.ncptl_verify
ncptl_permit_signal = _pyncptl.ncptl_permit_signal
ncptl_parse_command_line = _pyncptl.ncptl_parse_command_line
ncptl_time = _pyncptl.ncptl_time
ncptl_set_flag_after_usecs = _pyncptl.ncptl_set_flag_after_usecs
ncptl_udelay = _pyncptl.ncptl_udelay
ncptl_seed_random_task = _pyncptl.ncptl_seed_random_task
ncptl_random_task = _pyncptl.ncptl_random_task
ncptl_allocate_task_map = _pyncptl.ncptl_allocate_task_map
ncptl_virtual_to_physical = _pyncptl.ncptl_virtual_to_physical
ncptl_physical_to_virtual = _pyncptl.ncptl_physical_to_virtual
ncptl_assign_processor = _pyncptl.ncptl_assign_processor
ncptl_malloc = _pyncptl.ncptl_malloc
ncptl_free = _pyncptl.ncptl_free
ncptl_realloc = _pyncptl.ncptl_realloc
ncptl_malloc_message = _pyncptl.ncptl_malloc_message
ncptl_malloc_misaligned = _pyncptl.ncptl_malloc_misaligned
ncptl_get_message_buffer = _pyncptl.ncptl_get_message_buffer
ncptl_touch_data = _pyncptl.ncptl_touch_data
ncptl_touch_memory = _pyncptl.ncptl_touch_memory
ncptl_log_add_comment = _pyncptl.ncptl_log_add_comment
ncptl_log_open = _pyncptl.ncptl_log_open
ncptl_log_lookup_string = _pyncptl.ncptl_log_lookup_string
ncptl_log_generate_uuid = _pyncptl.ncptl_log_generate_uuid
ncptl_log_write = _pyncptl.ncptl_log_write
ncptl_log_write_prologue = _pyncptl.ncptl_log_write_prologue
ncptl_log_write_epilogue = _pyncptl.ncptl_log_write_epilogue
ncptl_log_compute_aggregates = _pyncptl.ncptl_log_compute_aggregates
ncptl_log_commit_data = _pyncptl.ncptl_log_commit_data
ncptl_log_close = _pyncptl.ncptl_log_close
ncptl_func_sqrt = _pyncptl.ncptl_func_sqrt
ncptl_dfunc_sqrt = _pyncptl.ncptl_dfunc_sqrt
ncptl_func_cbrt = _pyncptl.ncptl_func_cbrt
ncptl_dfunc_cbrt = _pyncptl.ncptl_dfunc_cbrt
ncptl_func_root = _pyncptl.ncptl_func_root
ncptl_dfunc_root = _pyncptl.ncptl_dfunc_root
ncptl_func_bits = _pyncptl.ncptl_func_bits
ncptl_dfunc_bits = _pyncptl.ncptl_dfunc_bits
ncptl_func_shift_left = _pyncptl.ncptl_func_shift_left
ncptl_dfunc_shift_left = _pyncptl.ncptl_dfunc_shift_left
ncptl_func_log10 = _pyncptl.ncptl_func_log10
ncptl_dfunc_log10 = _pyncptl.ncptl_dfunc_log10
ncptl_func_factor10 = _pyncptl.ncptl_func_factor10
ncptl_dfunc_factor10 = _pyncptl.ncptl_dfunc_factor10
ncptl_func_abs = _pyncptl.ncptl_func_abs
ncptl_dfunc_abs = _pyncptl.ncptl_dfunc_abs
ncptl_func_power = _pyncptl.ncptl_func_power
ncptl_dfunc_power = _pyncptl.ncptl_dfunc_power
ncptl_func_modulo = _pyncptl.ncptl_func_modulo
ncptl_dfunc_modulo = _pyncptl.ncptl_dfunc_modulo
ncptl_func_floor = _pyncptl.ncptl_func_floor
ncptl_dfunc_floor = _pyncptl.ncptl_dfunc_floor
ncptl_func_ceiling = _pyncptl.ncptl_func_ceiling
ncptl_dfunc_ceiling = _pyncptl.ncptl_dfunc_ceiling
ncptl_func_round = _pyncptl.ncptl_func_round
ncptl_dfunc_round = _pyncptl.ncptl_dfunc_round
ncptl_func_tree_parent = _pyncptl.ncptl_func_tree_parent
ncptl_dfunc_tree_parent = _pyncptl.ncptl_dfunc_tree_parent
ncptl_func_tree_child = _pyncptl.ncptl_func_tree_child
ncptl_dfunc_tree_child = _pyncptl.ncptl_dfunc_tree_child
ncptl_func_grid_coord = _pyncptl.ncptl_func_grid_coord
ncptl_dfunc_grid_coord = _pyncptl.ncptl_dfunc_grid_coord
ncptl_func_grid_neighbor = _pyncptl.ncptl_func_grid_neighbor
ncptl_dfunc_grid_neighbor = _pyncptl.ncptl_dfunc_grid_neighbor
ncptl_func_knomial_parent = _pyncptl.ncptl_func_knomial_parent
ncptl_dfunc_knomial_parent = _pyncptl.ncptl_dfunc_knomial_parent
ncptl_func_knomial_child = _pyncptl.ncptl_func_knomial_child
ncptl_dfunc_knomial_child = _pyncptl.ncptl_dfunc_knomial_child
ncptl_func_random_uniform = _pyncptl.ncptl_func_random_uniform
ncptl_dfunc_random_uniform = _pyncptl.ncptl_dfunc_random_uniform
ncptl_func_random_gaussian = _pyncptl.ncptl_func_random_gaussian
ncptl_dfunc_random_gaussian = _pyncptl.ncptl_dfunc_random_gaussian
ncptl_func_random_poisson = _pyncptl.ncptl_func_random_poisson
ncptl_dfunc_random_poisson = _pyncptl.ncptl_dfunc_random_poisson

cvar = _pyncptl.cvar

